In [30]:
import numpy as np
import trimesh

# attach to logger so trimesh messages will be printed to console

In [31]:
file_name = '/root/BreakingBad/dataset/everyday/BeerBottle/3f91158956ad7db0322747720d7d37e8/fractured_11/piece_0.obj'
from util.preprocessing import *

mesh = trimesh.load_mesh(file_name)

In [32]:

# is the current mesh watertight?
mesh.is_watertight

True

In [33]:

# what's the euler number for the mesh?
mesh.euler_number

0

In [34]:

# the convex hull is another Trimesh object that is available as a property
# lets compare the volume of our mesh with the volume of its convex hull
print(mesh.volume / mesh.convex_hull.volume)

0.35899428650346726


In [35]:

# since the mesh is watertight, it means there is a
# volumetric center of mass which we can set as the origin for our mesh
mesh.vertices -= mesh.center_mass

In [36]:

# what's the moment of inertia for the mesh?
mesh.moment_inertia

array([[ 2.48637105e-04, -3.23472898e-07,  2.55932455e-07],
       [-3.23472898e-07,  2.48419071e-04, -2.04810911e-06],
       [ 2.55932455e-07, -2.04810911e-06,  1.00296912e-04]])

In [37]:

# if there are multiple bodies in the mesh we can split the mesh by
# connected components of face adjacency
# since this example mesh is a single watertight body we get a list of one mesh
mesh.split()

array([<trimesh.Trimesh(vertices.shape=(9750, 3), faces.shape=(19500, 3))>],
      dtype=object)

In [38]:

# facets are groups of coplanar adjacent faces
# set each facet to a random color
# colors are 8 bit RGBA by default (n, 4) np.uint8
for facet in mesh.facets:
    mesh.visual.face_colors[facet] = trimesh.visual.random_color()

In [39]:

# preview mesh in an opengl window if you installed pyglet and scipy with pip
mesh.show()

In [40]:

# transform method can be passed a (4, 4) matrix and will cleanly apply the transform
mesh.apply_transform(trimesh.transformations.random_rotation_matrix())


<trimesh.Trimesh(vertices.shape=(9750, 3), faces.shape=(19500, 3))>

In [41]:

# axis aligned bounding box is available
mesh.bounding_box.extents


array([0.31955017, 0.43698601, 0.58592559])

In [42]:

# a minimum volume oriented bounding box also available
# primitives are subclasses of Trimesh objects which automatically generate
# faces and vertices from data stored in the 'primitive' attribute
mesh.bounding_box_oriented.primitive.extents

TrackedArray([0.25238224, 0.25344313, 0.58201621])

In [43]:

mesh.bounding_box_oriented.primitive.transform

TrackedArray([[ 9.28037449e-01, -3.15367243e-01, -1.98217042e-01,
                8.74279336e-04],
              [-3.72426344e-01, -7.95193639e-01, -4.78503599e-01,
                4.31713159e-03],
              [-6.71657038e-03,  5.17890508e-01, -8.55420545e-01,
                9.34167118e-03],
              [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
                1.00000000e+00]])

In [44]:

# show the mesh appended with its oriented bounding box
# the bounding box is a trimesh.primitives.Box object, which subclasses
# Trimesh and lazily evaluates to fill in vertices and faces when requested
# (press w in viewer to see triangles)
(mesh + mesh.bounding_box_oriented).show()

In [46]:
mesh.face_normals

array([[ 0.96901396, -0.22671791, -0.09803541],
       [ 0.93497096, -0.35420425, -0.01920035],
       [ 0.04108099, -0.51816815, -0.85429159],
       ...,
       [-0.95574006,  0.28814886,  0.05942368],
       [-0.95574006,  0.28814886,  0.05942368],
       [-0.95574006,  0.28814886,  0.05942368]])