In [3]:
import numpy as np

from sghr.p2p_reg import name2estimator
from sghr.Laplacian_TS import pair2globalT_cycle


n = 2

# Initialize a 2x2 pair transformation matrix with identity matrices
Ts = np.zeros([n, n, 4, 4])
for i in range(n):
    for j in range(n):
        Ts[i, j] = np.identity(4)

import jhutil;jhutil.jhprint(1111, Ts)
# Initialize a 2x2 weight matrix with 1s
weights = np.ones([n, n])

# Create a simple 2x2 score matrix with 1s
scoremat = np.ones([n, n])

# Create a simple 2x2 inlier ratio matrix with 1s
irs = np.ones([n, n])

# Set N_cyclegraph to 1
N_cyclegraph = 1

# Call the pair2globalT_cycle function
Tglobals, weights_out = pair2globalT_cycle(weights * scoremat * irs, Ts, N_cyclegraph)



1111  "array[2, 2, 4, 4] n=64 x∈[0., 1.000] μ=0.250 σ=0.433"
Tglobals:
[[[0. 0. 1. 0.]
  [1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 0. 1.]]

 [[0. 0. 1. 0.]
  [1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 0. 1.]]]
Weights out:
[[0.         0.         0.99998473]
 [0.         1.         0.99998473]
 [1.         0.         0.99998473]
 [1.         1.         0.99998473]]
